Exponential
google/distbench pull request #189
Opened 2023-06-09 18:01 UTC by pedrogzz18

Implemented the exponential distribution as an option for the interval_distribution on distbench_engine and a test for it.

2023-06-09 18:08 UTC, danmanj requested changes

2023-06-09 18:08 UTC, danmanj commented on distbench_test_sequencer_test.cc
> +  ASSERT_EQ(epx_server_echo->second.successful_rpc_samples_size(), 10);
what are these for? revert?

2023-06-09 18:08 UTC, danmanj commented on distbench_test_sequencer_test.cc
> +
blank lines? remove?

2023-06-09 18:08 UTC, danmanj commented on distbench_test_sequencer_test.cc
> +  a1->mutable_iterations()->set_open_loop_interval_ns(3'200'000);
3200000 is a constant used in 2 places. declare it as a const int?

2023-06-09 18:08 UTC, danmanj commented on distbench_test_sequencer_test.cc
> +      max_ts = time_intervals[i];
maybe declare a local interval variable and use it instead of time_intervals[i]

2023-06-09 18:08 UTC, danmanj commented on distbench_engine.cc
> +  if(interval_distribution == "exponential_distribution"){
avoid testing a string for equality in the inner loop, test it once, and store the result in the class.

2023-06-09 18:08 UTC, danmanj commented on distbench_engine.cc
> +    double num_gen = action_state->exponential_gen(*action_state->rand_gen) *
num_gen needs a better name.

2023-06-09 20:13 UTC, danmanj requested changes

2023-06-09 20:13 UTC, danmanj commented on distbench_engine.cc
> +  auto& interval_distribution = action_state->action->proto.iterations()
unused?

2023-06-09 20:13 UTC, danmanj commented on distbench_engine.cc
> +    action_state->next_iteration_time += absl::Nanoseconds(next_interval);
multiply period by result directly?

2023-06-09 20:13 UTC, danmanj commented on distbench_engine.h
> +    bool exponential;
is_exponential?

2023-06-09 20:13 UTC, danmanj commented on distbench_test_sequencer_test.cc
> +TEST(DistBenchTestSequencer, ExponenentialDistributionTest) {
reverse test for non-exponential?

2023-06-21 22:09 UTC, danmanj commented on distbench_engine.h
> +    bool is_exponential;
interval_is_exponential

2023-06-21 23:09 UTC, pedrogzz18 commented
this solves issue #198

2023-06-21 23:15 UTC, danmanj approved these changes

2023-06-21 23:15 UTC, merged